In [1]:
import numpy as np

 ##  One dimensional array

In [2]:
list1=[1, 2, 3, 4 , 5, 6, 7, 8]

In [3]:
list1[1:7:2]

[2, 4, 6]

In [4]:
array1 = np.array(list1)

In [5]:
array1[1:7:2]

array([2, 4, 6])

##    Multi Dimensional

In [6]:
list2 = [[1 ,2 ,3 , 4 ,5, 6, 7, 8],[1, 3, 5, 7, 9, 11, 13, 15]]

In [7]:
list2[0][5:]

[6, 7, 8]

In [8]:
array2 = np.array(list2)


In [9]:
array2

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 1,  3,  5,  7,  9, 11, 13, 15]])

In [10]:
array2[0][5:]

array([6, 7, 8])

In [11]:
array2[0 ,5:]

array([6, 7, 8])

In [12]:
array2[ :,1:4] # where : represents all row

array([[2, 3, 4],
       [3, 5, 7]])

In [13]:
odd_first_list =array2[0 , array2[0] % 2 !=0]
even_second_list =array2[1 , array2[1] % 2 ==0]

In [14]:
odd_first_list

array([1, 3, 5, 7])

In [15]:
even_second_list

array([], dtype=int32)

In [19]:
# [start : stop : step]
array2[:, 1::2]

array([[ 2,  4,  6,  8],
       [ 3,  7, 11, 15]])

In [20]:
list3=[[1,2,3,4,5,6,7,8],[1,3,5,7,9,11,13,15],[15,25,9999,376,19,420,786,555]]

In [21]:
array3 = np.array(list3)

In [22]:
array3

array([[   1,    2,    3,    4,    5,    6,    7,    8],
       [   1,    3,    5,    7,    9,   11,   13,   15],
       [  15,   25, 9999,  376,   19,  420,  786,  555]])

In [24]:
array3[1:, 4:7]

array([[  9,  11,  13],
       [ 19, 420, 786]])

In [25]:
array3.shape

(3, 8)

In [26]:
array3.shape[0]

3

In [35]:
list4 =[
    [[1,2,3,4],[5,6,7,8]],
    [[1,3,5,7],[9,11,13,15]],
    [[15,25,9999,376],[19,420,786,555]]
]

In [36]:
array4= np.array(list4)

In [37]:
array4.shape

(3, 2, 4)

In [38]:
array4.ndim

3

In [39]:
array4[ :, 2:3,1:3]

array([], shape=(3, 0, 2), dtype=int32)

In [41]:
array4[:2,:,1:3]

array([[[ 2,  3],
        [ 6,  7]],

       [[ 3,  5],
        [11, 13]]])