In [1]:
import numpy as np

In [9]:
a = np.array([[1,2,3],[4,5,6]])


In [10]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
a.shape

(2, 3)

In [4]:
a.dtype

dtype('int32')

In [5]:
a.ndim

2

In [6]:
a.flatten()

array([1, 2, 3, 4, 5, 6])

In [7]:
a.sum()

21

In [8]:
a.max()

6

In [11]:
a.max(axis=0)

array([4, 5, 6])

In [12]:
a.max(axis=1)

array([3, 6])

In [15]:
a.argmax(axis=1)
print(a.dtype)

int32


In [16]:
# NOTE: product of elements should be conserved
a.reshape((3,2))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [17]:
b= a.reshape((1,2,3))

In [18]:
b.shape

(1, 2, 3)

In [19]:
m= np.array([[1,2],[3,4]])
n= np.array([[5,6],[7,8]])

In [23]:
np.concatenate((m,n),axis=None)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [24]:
np.concatenate((m,n),axis=0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [25]:
np.concatenate((m,n),axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [32]:
a=a.reshape(6)


In [29]:
a

array([1, 2, 3, 4, 5, 6])

In [28]:
np.split(a,3)

[array([1, 2]), array([3, 4]), array([5, 6])]

In [33]:
string = 'hello how are you'


In [35]:
string.split('  ')

['hello how are you']

In [37]:
np.split(a , 3)

[array([1, 2]), array([3, 4]), array([5, 6])]

In [38]:
np.split (a, (2,5,7))

[array([1, 2]), array([3, 4, 5]), array([6]), array([], dtype=int32)]