In [1]:
import numpy as np

#  creating numpy arrays

####  np.array()

In [2]:
list1 = [1, 2, 3]
print(type(list1))
array1 = np.array(list1)
print(array1)
print(type(array1))
print(array1.ndim)

<class 'list'>
[1 2 3]
<class 'numpy.ndarray'>
1


In [3]:
list2 =[[1,2],[3,4]]
array2 = np.array(list2)
print(array2)
print(type(array2))
print(array2.ndim)

[[1 2]
 [3 4]]
<class 'numpy.ndarray'>
2


###  np.zeros()

In [6]:
np.zeros(5)


array([0., 0., 0., 0., 0.])

In [5]:
np.zeros((2, 3, 4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

###  np.ones()

In [7]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [8]:
np.ones((2 , 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

###  np.full()

In [10]:
np.full(5 , -2)

array([2, 2, 2, 2, 2])

In [12]:
np.full((2 , 3), -2)

array([[-2, -2, -2],
       [-2, -2, -2]])

###  np.arange()

In [14]:
# np.array(range(start . stop , step))
np.arange(5)

array([0, 1, 2, 3, 4])

In [15]:
np.arange(2, 10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.arange(2, 10, 2)

array([2, 4, 6, 8])

###  np.linspace()

In [19]:
# np.linspace(start, stop , num_of_elements_in_between)
np.linspace(1 , 10, 2)

array([ 1., 10.])

In [20]:
np.linspace(1 ,10 , 4)

array([ 1.,  4.,  7., 10.])

In [22]:
np.linspace((1,2), (5,10), num=5)

array([[ 1.,  2.],
       [ 2.,  4.],
       [ 3.,  6.],
       [ 4.,  8.],
       [ 5., 10.]])

###  np.diag()

In [23]:
np.diag([2, 3, 4, 5])

array([[2, 0, 0, 0],
       [0, 3, 0, 0],
       [0, 0, 4, 0],
       [0, 0, 0, 5]])

In [25]:
np.diag([2, 3, 4, 5], k=1)

array([[0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5],
       [0, 0, 0, 0, 0]])

In [26]:
np.diag([2, 3, 4, 5] , k=-1)

array([[0, 0, 0, 0, 0],
       [2, 0, 0, 0, 0],
       [0, 3, 0, 0, 0],
       [0, 0, 4, 0, 0],
       [0, 0, 0, 5, 0]])

###  np.eye()

In [27]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [28]:
np.eye(5, k=-1)

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

###  np.identity()

In [29]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

###  np.random.rand()

In [30]:
np.random.rand(2, 3)

array([[0.10864593, 0.92217959, 0.66949064],
       [0.36154039, 0.52298369, 0.94859042]])

In [31]:
np.random.rand(2, 3)

array([[0.07989651, 0.79234274, 0.50775762],
       [0.48495315, 0.05345454, 0.61807457]])

###  np.random.randint()

In [32]:
np.random.randint(2 ,7, size =(3, 7))

array([[2, 5, 6, 2, 6, 2, 3],
       [2, 4, 2, 3, 5, 3, 2],
       [4, 5, 5, 2, 6, 5, 5]])